export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_STUDENT_PRODUCTS = 'GET_STUDENT_PRODUCTS';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const FILTER_PRODUCTS = 'FILTER_PRODUCTS';
export const SET_ERROR = 'SET_ERROR';

export const GET_STUDENTS = 'GET_STUDENTS';
export const FILTER_STUDENTS = 'FILTER_STUDENTS';
